### ISSUE TITLE
Error occurred while enabling HoloDropsX v3.0.0

### ISSUE THREAD

**Issue by LOVE2CMOL** [ProfliX/HoloDropsX#3]
paper-1.17-Build#53
https://papermc.io/downloads

JAVA version:
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK-16.0.1+9 (build openj9-0.26.0, JRE 16 Linux amd64-64-Bit Compressed References 20210421_23 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - cea22090ecf based on jdk-16.0.1+9)

server log:
[15:52:06] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:52:07] [main/INFO]: Reloading ResourceManager: Default, bukkit
[15:52:09] [Worker-Main-4/INFO]: Loaded 7 recipes
[15:52:12] [Server thread/INFO]: Starting minecraft server version 1.17
[15:52:12] [Server thread/INFO]: Loading properties
[15:52:13] [Server thread/INFO]: This server is running Paper version git-Paper-53 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0ad5526)
[15:52:13] [Server thread/INFO]: Using 4 threads for Netty based IO
[15:52:13] [Server thread/INFO]: Server Ping Player Sample Count: 12
[15:52:13] [Server thread/INFO]: Debug logging is disabled
[15:52:13] [Server thread/INFO]: Default game type: SURVIVAL
[15:52:13] [Server thread/INFO]: Generating keypair
[15:52:13] [Server thread/INFO]: Starting Minecraft server on *:25565
[15:52:13] [Server thread/INFO]: Using epoll channel type
[15:52:15] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
.....................
[15:52:41] [Server thread/INFO]: [HoloDropsX] Enabling HoloDropsX v3.0.0
[15:52:41] [Server thread/ERROR]: Error occurred while enabling HoloDropsX v3.0.0 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant dev.proflix.holodropsx.libs.xseries.XMaterial.GRASS_PATH
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at dev.proflix.holodropsx.libs.xseries.XMaterial.valueOf(XMaterial.java:68) ~[?:?]
	at dev.proflix.holodropsx.util.Settings.initialize(Settings.java:52) ~[?:?]
	at dev.proflix.holodropsx.Main.onEnable(Main.java:41) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-53]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-53]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-53]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-53]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-53]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-53]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-53]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-53]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-53]
	at net.minecraft.server.MinecraftServer$$Lambda$3654/0x000000000e12e4d0.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:853) [?:?]
[15:52:41] [Server thread/INFO]: [HoloDropsX] Disabling HoloDropsX v3.0.0
.....................

**Comment by LOVE2CMOL** [comment]
Compile by v3.0.1

[16:12:33] [Server thread/ERROR]: Error occurred while enabling HoloDropsX v3.0.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant dev.proflix.holodropsx.libs.xseries.XMaterial.GRASS_PATH
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at dev.proflix.holodropsx.libs.xseries.XMaterial.valueOf(XMaterial.java:68) ~[?:?]
	at dev.proflix.holodropsx.util.Settings.initialize(Settings.java:52) ~[?:?]
	at dev.proflix.holodropsx.Main.onEnable(Main.java:42) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-53]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-53]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-53]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-53]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-53]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-53]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-53]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-53]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-53]
	at net.minecraft.server.MinecraftServer$$Lambda$3656/0x00000000bdd1f630.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:853) [?:?]
[16:12:33] [Server thread/INFO]: [HoloDropsX] Disabling HoloDropsX v3.0.1

**Comment by ProfliX** [comment]
> 
> 
> paper-1.17-Build#53
> https://papermc.io/downloads
> 
> JAVA version:
> openjdk version "16.0.1" 2021-04-20
> OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
> Eclipse OpenJ9 VM AdoptOpenJDK-16.0.1+9 (build openj9-0.26.0, JRE 16 Linux amd64-64-Bit Compressed References 20210421_23 (JIT enabled, AOT enabled)
> OpenJ9 - b4cc246d9
> OMR - 162e6f729
> JCL - cea22090ecf based on jdk-16.0.1+9)
> 
> server log:
> [15:52:06] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
> [15:52:07] [main/INFO]: Reloading ResourceManager: Default, bukkit
> [15:52:09] [Worker-Main-4/INFO]: Loaded 7 recipes
> [15:52:12] [Server thread/INFO]: Starting minecraft server version 1.17
> [15:52:12] [Server thread/INFO]: Loading properties
> [15:52:13] [Server thread/INFO]: This server is running Paper version git-Paper-53 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0ad5526)
> [15:52:13] [Server thread/INFO]: Using 4 threads for Netty based IO
> [15:52:13] [Server thread/INFO]: Server Ping Player Sample Count: 12
> [15:52:13] [Server thread/INFO]: Debug logging is disabled
> [15:52:13] [Server thread/INFO]: Default game type: SURVIVAL
> [15:52:13] [Server thread/INFO]: Generating keypair
> [15:52:13] [Server thread/INFO]: Starting Minecraft server on *:25565
> [15:52:13] [Server thread/INFO]: Using epoll channel type
> [15:52:15] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
> .....................
> [15:52:41] [Server thread/INFO]: [HoloDropsX] Enabling HoloDropsX v3.0.0
> [15:52:41] [Server thread/ERROR]: Error occurred while enabling HoloDropsX v3.0.0 (Is it up to date?)
> java.lang.IllegalArgumentException: No enum constant dev.proflix.holodropsx.libs.xseries.XMaterial.GRASS_PATH
> at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
> at dev.proflix.holodropsx.libs.xseries.XMaterial.valueOf(XMaterial.java:68) ~[?:?]
> at dev.proflix.holodropsx.util.Settings.initialize(Settings.java:52) ~[?:?]
> at dev.proflix.holodropsx.Main.onEnable(Main.java:41) ~[?:?]
> at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-53]
> at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-53]
> at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-53]
> at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-53]
> at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-53]
> at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-53]
> at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-53]
> at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-53]
> at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-53]
> at net.minecraft.server.MinecraftServer$$Lambda$3654/0x000000000e12e4d0.run(Unknown Source) ~[?:?]
> at java.lang.Thread.run(Thread.java:853) [?:?]
> [15:52:41] [Server thread/INFO]: [HoloDropsX] Disabling HoloDropsX v3.0.0
> .....................

Bug will be fixed in no time (btw plugin was never tested on 1.17)

**Comment by ProfliX** [comment]
Well, grass path material `does not` exist. Just reset the config. Or find in item-names section GRASS_PATH and delete it. This plugin uses custom materials which give support for `cross-versions` meaning that you should use material names from [here](https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XMaterial.java). But if you don't want it just, delete the config and restart the server, config will automatically generate all items by default. Which can be checked with /hdxcheck (if you have permission holodropsx.check).

**Comment by LOVE2CMOL** [comment]
> Well, grass path material `does not` exist. Just reset the config. Or find in item-names section GRASS_PATH and delete it. This plugin uses custom materials which give support for `cross-versions` meaning that you should use material names from [here](https://javadoc.io/doc/com.github.cryptomorin/XSeries/latest/com/cryptomorin/xseries/XMaterial.html). But if you don't want it just, delete the config and restart the server, config will automatically generate all items by default. Which can be checked with /hdxcheck (if you have permission holodropsx.check). Make sure you backup before deleting the config.

okay thk 😀

**Comment by ProfliX** [comment]
> 
> 
> > Well, grass path material `does not` exist. Just reset the config. Or find in item-names section GRASS_PATH and delete it. This plugin uses custom materials which give support for `cross-versions` meaning that you should use material names from [here](https://javadoc.io/doc/com.github.cryptomorin/XSeries/latest/com/cryptomorin/xseries/XMaterial.html). But if you don't want it just, delete the config and restart the server, config will automatically generate all items by default. Which can be checked with /hdxcheck (if you have permission holodropsx.check). Make sure you backup before deleting the config.
> 
> okay thk grinning

Yw :+1:  :smile:
